# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fraud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66raud.proto\"[\n\x0c\x46raudRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x02\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x12\n\nip_address\x18\x03 \x01(\t\x12\x15\n\rrecent_orders\x18\x04 \x01(\x05\";\n\rFraudResponse\x12\x12\n\nrisk_score\x18\x01 \x01(\x02\x12\x16\n\x0erecommendation\x18\x02 \x01(\t2;\n\x0c\x46raudService\x12+\n\nCheckFraud\x12\r.FraudRequest\x1a\x0e.FraudResponseB \n\x10\x63om.procart.grpcB\nFraudProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.procart.grpcB\nFraudProtoP\001'
  _globals['_FRAUDREQUEST']._serialized_start=15
  _globals['_FRAUDREQUEST']._serialized_end=106
  _globals['_FRAUDRESPONSE']._serialized_start=108
  _globals['_FRAUDRESPONSE']._serialized_end=167
  _globals['_FRAUDSERVICE']._serialized_start=169
  _globals['_FRAUDSERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
